layout_spectrum: 0.9580224
typography_spectrum: 0.6208318
color:
  saturation: 0.6072761
  brandStrength: 0.5188364
  lightness: 0.6511194
  rhythmicContrast: 0.8091016
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Sounds Amazing
